### ISSUE TITLE
Nonlinearity missing?

### ISSUE THREAD

**Issue by mha-py** [louislva/deepmind-perceiver#1]
Hey!
Great code! Am i wrong, or is there a nonlinearity missing between linear1 and linear2 in the Attention Block?

```python
    def forward(self, x, z_input):
        x = self.layer_norm_x(x)
        z = self.layer_norm_1(z_input)
        z, _ = self.attention(z, x, x)

        z = self.dropout(z)
        z = self.linear1(z)
        # z = F.gelu(z) ??

        z = self.layer_norm_2(z)
        z = self.linear2(z)
        z = F.gelu(z)
        z = self.dropout(z)
        z = self.linear3(z)

        return z + z_input
```

**Comment by louislva** [comment]
Hey @mha-py, sorry for the late reply and thanks for the kind words. Somehow I did not get a notification. I don't think there is supposed to be a non-linearity there. 

This is from the paper: 

> **B. Architectural details**
The Perceiver consists of two modules: a cross-attention module and a transformer. In the cross-attention module, inputs are first processed with layer norm (Ba et al., 2016) before being passed through linear layers to produce each of the query, key, and value inputs to the QKV cross-attention operation. The output of attention is passed through an additional linear layer. We apply dropout to this linear layer.
> 
> In the self-attention block, inputs are processed with layer norm and passed through query, key, and value layers before being used to compute QKV self-attention. The output is passed through another linear layer, to which dropout is applied.
> 
> Each cross-attention and self-attention block is followed by a dense (multi-layer perceptron) block. In the dense block, inputs are processed with layer norm, passed through a linear layer, activated with a GELU nonlinearity (Hendrycks & Gimpel, 2016), and passed through a final linear layer (to which dropout is applied).

The cross attention and self-attention function the same, and are implemented with the first two paragraphs/blocks of code. They describe no non-linearity there, but they do describe one in the multi-layer perceptron (the last block of code).
